mysql:
  driver: mysql
  url: 'USER:PASSWORD(HOST:PORT)/DATABASE'
  # connection max life time: default 3 minutes
  max-life-time: 3
  # max open connections: default 10
  max-open-connections: 10
  # max idle connections: default 10
  max-idle-connections: 10

# 需要保存汇率的货币
currency-dst: CNY,USD,GBP